### ISSUE TITLE
Which version of the Ignition Gazebo is used?

### ISSUE THREAD

**Issue by liuqy1994** [Auterion/px4-simulation-ignition#15]
**Thank you very much for contributing an interesting project, but I'm having a bit of a problem with reproduction.

I needed this error when I compiled according to the [instructions](https://docs.px4.io/master/en/simulation/ignition_gazebo.html) in this manual.**

`
XXX@XXXXXXXX:~/PX4-Autopilot$ VERBOSE_SIM=1 make px4_sitl ignition
[0/4] Performing build step for 'simulation-ignition'
[0/1] Re-running CMake...
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Searching for dependencies of ignition-plugin1
-- Searching for <ignition-plugin1> component [register]
-- Looking for ignition-plugin1-register -- found version 1.2.1
-- Searching for dependencies of ignition-plugin1-register
-- Looking for ignition-gazebo5 -- found version 5.3.0
-- Searching for dependencies of ignition-gazebo5
-- Looking for ignition-math6 -- found version 6.9.2
-- Searching for dependencies of ignition-math6
-- Looking for ignition-utils1 -- found version 1.1.0
-- Searching for dependencies of ignition-utils1
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Searching for dependencies of ignition-plugin1
-- Searching for <ignition-plugin1> component [loader]
-- Looking for ignition-plugin1-loader -- found version 1.2.1
-- Searching for dependencies of ignition-plugin1-loader
-- Searching for <ignition-plugin1> component [register]
-- Looking for ignition-transport10 -- found version 10.1.0
-- Searching for dependencies of ignition-transport10
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3") 
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Looking for ignition-utils1 -- found version 1.1.0
-- Searching for dependencies of ignition-utils1
-- Searching for <ignition-utils1> component [cli]
-- Looking for ignition-utils1-cli -- found version 1.1.0
-- Searching for dependencies of ignition-utils1-cli
-- Looking for ignition-msgs7 -- found version 7.2.0
-- Searching for dependencies of ignition-msgs7
-- Looking for ignition-math6 -- found version 6.9.2
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Searching for <ignition-transport10> component [log]
-- Looking for ignition-transport10-log -- found version 10.1.0
-- Searching for dependencies of ignition-transport10-log
-- Looking for ignition-msgs7 -- found version 7.2.0
-- Looking for ignition-common4 -- found version 4.4.0
-- Searching for dependencies of ignition-common4
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Searching for <ignition-common4> component [profiler]
-- Looking for ignition-common4-profiler -- found version 4.4.0
-- Searching for dependencies of ignition-common4-profiler
-- Searching for <ignition-common4> component [events]
-- Looking for ignition-common4-events -- found version 4.4.0
-- Searching for dependencies of ignition-common4-events
-- Looking for ignition-math6 -- found version 6.9.2
-- Searching for <ignition-common4> component [av]
-- Looking for ignition-common4-av -- found version 4.4.0
-- Searching for dependencies of ignition-common4-av
-- Checking for module 'libswscale'
--   Found libswscale, version 5.5.100
-- Checking for module 'libavdevice >= 56.4.100'
--   Found libavdevice , version 58.8.100
-- Checking for module 'libavformat'
--   Found libavformat, version 58.29.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.54.100
-- Checking for module 'libavutil'
--   Found libavutil, version 56.31.100
-- Looking for ignition-fuel_tools6 -- found version 6.1.0
-- Searching for dependencies of ignition-fuel_tools6
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Looking for ignition-common4 -- found version 4.4.0
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-msgs7 -- found version 7.2.0
-- Looking for ignition-gui5 -- found version 5.3.0
-- Searching for dependencies of ignition-gui5
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-common4 -- found version 4.4.0
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Looking for ignition-transport10 -- found version 10.1.0
-- Looking for ignition-rendering5 -- found version 5.2.0
-- Searching for dependencies of ignition-rendering5
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-common4 -- found version 4.4.0
-- Searching for dependencies of ignition-common4
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Searching for <ignition-common4> component [graphics]
-- Looking for ignition-common4-graphics -- found version 4.4.0
-- Searching for dependencies of ignition-common4-graphics
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-utils1 -- found version 1.1.0
-- Searching for <ignition-common4> component [events]
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Searching for dependencies of ignition-plugin1
-- Searching for <ignition-plugin1> component [all]
-- Looking for all libraries of ignition-plugin1 -- found version 1.2.1
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Searching for <ignition-rendering5> component [ogre]
-- Looking for ignition-rendering5-ogre -- found version 5.2.0
-- Searching for dependencies of ignition-rendering5-ogre
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/ignition-rendering5-ogre/ignition-rendering5-ogre-config.cmake:114 (find_package)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/ignition-rendering5/ignition-rendering5-config.cmake:204 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/ignition-gui5/ignition-gui5-config.cmake:98 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/ignition-gazebo5/ignition-gazebo5-config.cmake:98 (find_package)
  CMakeLists.txt:12 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for ignition-msgs7 -- found version 7.2.0
-- Looking for ignition-physics4 -- found version 4.3.0
-- Searching for dependencies of ignition-physics4
-- Looking for ignition-math6 -- found version 6.9.2
-- Searching for dependencies of ignition-math6
-- Searching for <ignition-math6> component [eigen3]
-- Looking for ignition-math6-eigen3 -- found version 6.9.2
-- Searching for dependencies of ignition-math6-eigen3
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Looking for ignition-utils1 -- found version 1.1.0
-- Searching for <ignition-physics4> component [heightmap]
-- Looking for ignition-physics4-heightmap -- found version 4.3.0
-- Searching for dependencies of ignition-physics4-heightmap
-- Looking for ignition-common4 -- found version 4.4.0
-- Searching for <ignition-physics4> component [mesh]
-- Looking for ignition-physics4-mesh -- found version 4.3.0
-- Searching for dependencies of ignition-physics4-mesh
-- Looking for ignition-common4 -- found version 4.4.0
-- Searching for <ignition-physics4> component [sdf]
-- Looking for ignition-physics4-sdf -- found version 4.3.0
-- Searching for dependencies of ignition-physics4-sdf
-- Looking for ignition-sensors5 -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-common4 -- found version 4.4.0
-- Looking for ignition-transport10 -- found version 10.1.0
-- Looking for ignition-rendering5 -- found version 5.2.0
-- Looking for ignition-msgs7 -- found version 7.2.0
-- Looking for ignition-plugin1 -- found version 1.2.1
-- Searching for <ignition-sensors5> component [rendering]
-- Looking for ignition-sensors5-rendering -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-rendering
-- Searching for <ignition-sensors5> component [air_pressure]
-- Looking for ignition-sensors5-air_pressure -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-air_pressure
-- Searching for <ignition-sensors5> component [altimeter]
-- Looking for ignition-sensors5-altimeter -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-altimeter
-- Searching for <ignition-sensors5> component [camera]
-- Looking for ignition-sensors5-camera -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-camera
-- Searching for <ignition-sensors5> component [gpu_lidar]
-- Looking for ignition-sensors5-gpu_lidar -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-gpu_lidar
-- Searching for <ignition-sensors5> component [imu]
-- Looking for ignition-sensors5-imu -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-imu
-- Searching for <ignition-sensors5> component [logical_camera]
-- Looking for ignition-sensors5-logical_camera -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-logical_camera
-- Searching for <ignition-sensors5> component [magnetometer]
-- Looking for ignition-sensors5-magnetometer -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-magnetometer
-- Searching for <ignition-sensors5> component [depth_camera]
-- Looking for ignition-sensors5-depth_camera -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-depth_camera
-- Searching for <ignition-sensors5> component [thermal_camera]
-- Looking for ignition-sensors5-thermal_camera -- found version 5.1.0
-- Searching for dependencies of ignition-sensors5-thermal_camera
-- Looking for ignition-rendering5 -- found version 5.2.0
-- Looking for ignition-math6 -- found version 6.9.2
-- Looking for ignition-utils1 -- found version 1.1.0
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hyy/PX4-Autopilot/build/px4_sitl_default/build_ign_gazebo
[7/19] Building CXX object msgs/CMakeFiles/sensor_msgs.dir/MagneticField.pb.cc.o
FAILED: msgs/CMakeFiles/sensor_msgs.dir/MagneticField.pb.cc.o 
/usr/bin/c++  -Dsensor_msgs_EXPORTS  -fPIC -MD -MT msgs/CMakeFiles/sensor_msgs.dir/MagneticField.pb.cc.o -MF msgs/CMakeFiles/sensor_msgs.dir/MagneticField.pb.cc.o.d -o msgs/CMakeFiles/sensor_msgs.dir/MagneticField.pb.cc.o -c msgs/MagneticField.pb.cc
In file included from msgs/MagneticField.pb.cc:4:
msgs/MagneticField.pb.h:33:10: fatal error: ignition/msgs/vector3d.pb.h: No such file or directory

ninja: build stopped: subcommand failed.
FAILED: external/Stamp/simulation-ignition/simulation-ignition-build 
cd /home/hyy/PX4-Autopilot/build/px4_sitl_default/build_ign_gazebo && /usr/bin/cmake --build /home/hyy/PX4-Autopilot/build/px4_sitl_default/build_ign_gazebo -- -j 8
ninja: build stopped: subcommand failed.
make: *** [Makefile:230: px4_sitl] Error 1
`

I speculate that it is possible to use different Ignition Gazebo versions. I am using version of Ignition Gazebo is 6.2.1. 
But there is Ignition Gazebo is 5 in the [Cmakelist.txt](https://github.com/Auterion/px4-simulation-ignition/blob/master/CMakeLists.txt). So I manually changed ignition-gazebo5 to Ignition -gazebo6. And it compiled successfully.

![image](https://user-images.githubusercontent.com/23204047/143240712-7a833287-b9e3-440d-86f3-39ff4199e93d.png)

However, the quadrotor cant takeoff, the output of `commander check` is
`pxh> commander check
WARN  [PreFlightCheck] Preflight Fail: Accel 0 inconsistent - Check Cal
INFO  [commander] Preflight check: FAILED
INFO  [commander] Prearm check: OK
INFO  [HealthFlags] DEVICE		STATUS
INFO  [HealthFlags] ----------------------------------
INFO  [HealthFlags] GYRO:		 	
INFO  [HealthFlags] ACC:		 	
INFO  [HealthFlags] MAG:		EN	OK
INFO  [HealthFlags] PRESS:		EN	OK
INFO  [HealthFlags] AIRSP:		 	
INFO  [HealthFlags] GPS:		 	
INFO  [HealthFlags] OPT:		 	
INFO  [HealthFlags] VIO:		 	
INFO  [HealthFlags] LASER:		 	
INFO  [HealthFlags] GTRUTH:		 	
INFO  [HealthFlags] RATES:		 	
INFO  [HealthFlags] ATT:		 	
INFO  [HealthFlags] YAW:		 	
INFO  [HealthFlags] ALTCTL:		 	
INFO  [HealthFlags] POS:		 	
INFO  [HealthFlags] MOT:		 	
INFO  [HealthFlags] RC  :		 	
INFO  [HealthFlags] GYRO2:		 	
INFO  [HealthFlags] ACC2:		 	
INFO  [HealthFlags] MAG2:		 	OK
INFO  [HealthFlags] GEOFENCE:		 	
INFO  [HealthFlags] AHRS:		EN	ERR
INFO  [HealthFlags] TERRAIN:		 	
INFO  [HealthFlags] REVMOT:		 	
INFO  [HealthFlags] LOGGIN:		 	
INFO  [HealthFlags] BATT:		 	
INFO  [HealthFlags] PROX:		 	
INFO  [HealthFlags] SATCOM:		 	
INFO  [HealthFlags] PREARM:		EN	ERR
INFO  [HealthFlags] OBSAVD:		 	
pxh> `
![image](https://user-images.githubusercontent.com/23204047/143241084-db0db38a-4ad9-471f-a362-161432cccd8a.png)
I think this is due to the plugin for the emulator not working properly. I am new to this and any helpful information would be appreciated.

**Comment by liuqy1994** [comment]
Is there anyone who would like to provide some documentation and information? pls

**Comment by Jaeyoung-Lim** [comment]
@liuqy1994 As written on the documentation from the readme, ignition edifice is the correct version to use: http://docs.px4.io/master/en/simulation/ignition_gazebo.html

**Comment by liuqy1994** [comment]
Thank you very much for your reply! But if I do nothing before ` make px4_sitl ignition`, the following error will occur:

```
XXX@hyy-NUC11PAHi7:~/PX4-Autopilot_host$ make px4_sitl ignition
[0/4] Performing build step for 'simulation-ignition'
ninja: no work to do.
[3/4] cd /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/tmp && /home/hyy/PX4-Autopilot... none none /home/hyy/PX4-Autopilot_host /home/hyy/PX4-Autopilot_host/build/px4_sitl_default
SITL ARGS
sitl_bin: /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/bin/px4
debugger: none
program: ignition
model: none
world: none
src_path: /home/hyy/PX4-Autopilot_host
build_path: /home/hyy/PX4-Autopilot_host/build/px4_sitl_default
empty model, setting iris as default
Ignition Gazebo
LD_LIBRARY_PATH /opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/XXX/PX4-Autopilot_host/build/px4_sitl_default/build_ign_gazebo
SITL COMMAND: "/home/XXX/PX4-Autopilot_host/build/px4_sitl_default/bin/px4" "/home/XXX/PX4-Autopilot_host/build/px4_sitl_default"/etc -s etc/init.d-posix/rcS -t "/home/XXX/PX4-Autopilot_host"/test_data
Creating symlink /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/etc -> /home/hyy/PX4-Autopilot_host/build/px4_sitl

_____  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [init] found model autostart file as SYS_AUTOSTART=10016
INFO  [param] selected parameter default file eeprom/parameters_10016
INFO  [parameters] BSON document size 446 bytes, decoded 446 bytes
[param] Loaded: eeprom/parameters_10016
INFO  [dataman] data manager file './dataman' size is 11798680 bytes
PX4 SIM HOST: localhost
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: ignition/msgs/actor.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Stack trace (most recent call last):
#31   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffa270b4, in ignition::gazebo::v6::LevelManager::LoadActiveEntities(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#30   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffa831c1, in ignition::gazebo::v6::SdfEntityCreator::CreateEntities(sdf::v12::Model const*)
#29   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffa97130, in void ignition::gazebo::v6::EventManager::Emit<ignition::common::EventT<void (unsigned long, std::shared_ptr<sdf::v12::Element>), ignition::gazebo::v6::events::LoadPluginsTag>, unsigned long const&, std::shared_ptr<sdf::v12::Element> const&>(unsigned long const&, std::shared_ptr<sdf::v12::Element> const&)
#28   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffab1a09, in ignition::gazebo::v6::SimulationRunner::LoadPlugins(unsigned long, std::shared_ptr<sdf::v12::Element> const&)
#27   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffab094b, in ignition::gazebo::v6::SimulationRunner::LoadPlugin(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<sdf::v12::Element> const&)
#26   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffacce58, in ignition::gazebo::v6::SystemLoader::LoadPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<sdf::v12::Element> const&)
#25   Object "/lib/x86_64-linux-gnu/libignition-gazebo6.so.6", at 0x7fb1ffacd76c, in 
#24   Object "/lib/x86_64-linux-gnu/libignition-plugin1-loader.so.1", at 0x7fb1fd0aa670, in ignition::plugin::Loader::LoadLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#23   Object "/lib/x86_64-linux-gnu/libignition-plugin1-loader.so.1", at 0x7fb1fd0a9a7d, in ignition::plugin::Loader::Implementation::LoadLib(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#22   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb204e0b3d9, in dlopen
#21   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb204e0bb58, in 
#20   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb205027982, in _dl_catch_error
#19   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb2050278b7, in _dl_catch_exception
#18   Object "/lib/x86_64-linux-gnu/libdl.so.2", at 0x7fb204e0b34b, in 
#17   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb2054765f9, in 
#16   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb2050278b7, in _dl_catch_exception
#15   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb2054770be, in 
#14   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb205027914, in _dl_catch_exception
#13   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb205472c90, in 
#12   Object "/lib64/ld-linux-x86-64.so.2", at 0x7fb205472b89, in 
#11   Object "/lib/x86_64-linux-gnu/libignition-msgs7.so.7", at 0x7fb1d923b458, in void std::call_once<void (&)()>(std::once_flag&, void (&)())
#10   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fb204eb347e, in 
#9    Object "/lib/x86_64-linux-gnu/libignition-msgs7.so.7", at 0x7fb1d92360dd, in protobuf_ignition_2fmsgs_2factor_2eproto::AddDescriptorsImpl()
#8    Object "/lib/x86_64-linux-gnu/libprotobuf.so.17", at 0x7fb1fee1087d, in 
#7    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fb20069f5a9, in _Unwind_Resume
#6    Object "/lib/x86_64-linux-gnu/libgcc_s.so.1", at 0x7fb20069ebee, in 
#5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb200752d20, in __gxx_personality_v0
#4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb200752368, in 
#3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb20075338b, in 
#2    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7fb200747910, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb204ee9858, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb204f0a18b, in gsignal
Aborted (Signal sent by tkill() 1203354 1000)
^CERROR [px4] Startup script returned with return value: 2
ninja: build stopped: interrupted by user.
make: *** [Makefile:230: px4_sitl] Interrupt
```
![image](https://user-images.githubusercontent.com/23204047/143669491-96a4acd0-c95f-48e7-bf42-3057251b03c8.png)

 Also, I checked that the version of ign gazeb used is 6.2.0.

```
hyy@hyy-NUC11PAHi7:~$ ign gazebo --version
Ignition Gazebo, version 6.2.0
Copyright (C) 2018 Open Source Robotics Foundation.
Released under the Apache 2.0 License.
```
![image](https://user-images.githubusercontent.com/23204047/143669567-f0e89a61-1478-4a70-8256-9061fa8ecd8c.png)

However, the version used in the simulation is 5.X. (`find_package(ignition-gazebo5 REQUIRED)`) in the [Cmakelist.txt](https://github.com/Auterion/px4-simulation-ignition/blob/master/CMakeLists.txt),  so [Cmakelist.txt](https://github.com/Auterion/px4-simulation-ignition/blob/master/CMakeLists.txt)  will not compile successfully until after it has been modified.

The last thing that is confusing is the ability to execute command `make px4_sitl ignition` in Docker and get success. So, I think this error is the cause of version inconsistency, so how can I fix it? 

THX!

**Comment by liuqy1994** [comment]
After I modified the gazebo version and msg version in both CMakelist.txt and CMakelist.txt, the result was a successful compilation.

```
hyy@hyy-NUC11PAHi7:~/PX4-Autopilot_host$ make px4_sitl ignition
[0/4] Performing build step for 'simulation-ignition'
ninja: no work to do.
[3/4] cd /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/tmp && /home/hyy/PX4-Autopilot... none none /home/hyy/PX4-Autopilot_host /home/hyy/PX4-Autopilot_host/build/px4_sitl_default
SITL ARGS
sitl_bin: /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/bin/px4
debugger: none
program: ignition
model: none
world: none
src_path: /home/hyy/PX4-Autopilot_host
build_path: /home/hyy/PX4-Autopilot_host/build/px4_sitl_default
empty model, setting iris as default
Ignition Gazebo
LD_LIBRARY_PATH /opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/hyy/PX4-Autopilot_host/build/px4_sitl_default/build_ign_gazebo
SITL COMMAND: "/home/hyy/PX4-Autopilot_host/build/px4_sitl_default/bin/px4" "/home/hyy/PX4-Autopilot_host/build/px4_sitl_default"/etc -s etc/init.d-posix/rcS -t "/home/hyy/PX4-Autopilot_host"/test_data
Creating symlink /home/hyy/PX4-Autopilot_host/build/px4_sitl_default/etc -> /home/hyy/PX4-Autopilot_host/build/px4_sitl

_____  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [init] found model autostart file as SYS_AUTOSTART=10016
INFO  [param] selected parameter default file eeprom/parameters_10016
INFO  [parameters] BSON document size 467 bytes, decoded 467 bytes
[param] Loaded: eeprom/parameters_10016
INFO  [dataman] data manager file './dataman' size is 11798680 bytes
PX4 SIM HOST: localhost
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
INFO  [simulator] Simulator connected on TCP port 4560.
../src/intel/isl/isl.c:2023: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
INFO  [commander] LED: open /dev/led0 failed (22)
INFO  [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO  [init] setting PWM_AUX_OUT none
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 18570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [mavlink] mode: Onboard, data rate: 4000 B/s on udp port 14280 remote port 14030
INFO  [mavlink] mode: Gimbal, data rate: 400000 B/s on udp port 13030 remote port 13280
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log (type: full)
INFO  [logger] [logger] ./log/2021-11-27/06_00_49.ulg   
INFO  [logger] Opened full log file: ./log/2021-11-27/06_00_49.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_{i}_BROADCAST = 1 to enable network)
INFO  [mavlink] MAVLink only on localhost (set param MAV_{i}_BROADCAST = 1 to enable network)
INFO  [px4] Startup script returned successfully
pxh> INFO  [tone_alarm] home set
WARN  [flight_mode_manager] Auto activation failed with error: Activation Failed
WARN  [flight_mode_manager] Position-Ctrl activation failed with error: Activation Failed
WARN  [flight_mode_manager] Altitude-Ctrl activation failed with error: Activation Failed
INFO  [tone_alarm] notify negative

pxh> 
```
![image](https://user-images.githubusercontent.com/23204047/143670157-e35ae41f-261e-4add-9253-86b0b12b5fea.png)

However, after typing the`commander takeoff` command, there is no response from the quadrotor. The output of the console looks like this:
```
pxh> commander takeoff
pxh> INFO  [commander] Armed by internal command        
INFO  [navigator] Using minimum takeoff altitude: 2.50 m        
INFO  [commander] Disarmed by auto preflight disarming  
INFO  [logger] closed logfile, bytes written: 18670875

```
Then check `commander check`:
```
pxh> commander check
INFO  [commander] Preflight check: OK
INFO  [commander] Prearm check: OK
INFO  [HealthFlags] DEVICE              STATUS
INFO  [HealthFlags] ----------------------------------
INFO  [HealthFlags] GYRO:                       
INFO  [HealthFlags] ACC:                        
INFO  [HealthFlags] MAG:                EN      OK
INFO  [HealthFlags] PRESS:              EN      OK
INFO  [HealthFlags] AIRSP:                      
INFO  [HealthFlags] GPS:                        OK
INFO  [HealthFlags] OPT:                        
INFO  [HealthFlags] VIO:                        
INFO  [HealthFlags] LASER:                      
INFO  [HealthFlags] GTRUTH:                     
INFO  [HealthFlags] RATES:                      
INFO  [HealthFlags] ATT:                        
INFO  [HealthFlags] YAW:                        
INFO  [HealthFlags] ALTCTL:                     
INFO  [HealthFlags] POS:                        
INFO  [HealthFlags] MOT:                        
INFO  [HealthFlags] RC  :                       
INFO  [HealthFlags] GYRO2:                      
INFO  [HealthFlags] ACC2:                       
INFO  [HealthFlags] MAG2:                       OK
INFO  [HealthFlags] GEOFENCE:                   
INFO  [HealthFlags] AHRS:               EN      OK
INFO  [HealthFlags] TERRAIN:                    
INFO  [HealthFlags] REVMOT:                     
INFO  [HealthFlags] LOGGIN:                     
INFO  [HealthFlags] BATT:                       
INFO  [HealthFlags] PROX:                       
INFO  [HealthFlags] SATCOM:                     
INFO  [HealthFlags] PREARM:             EN      OK
INFO  [HealthFlags] OBSAVD:                     
pxh> 
```
At last, I have no idea. /sad

**Comment by Jaeyoung-Lim** [comment]
@liuqy1994  Would you be able to make a PR with the Cmake fixes? Lets see what happens in the CI

**Comment by liuqy1994** [comment]
Very happy to do so, I have submitted a PR. :)

**Comment by Jaeyoung-Lim** [comment]
@liuqy1994 Can you confirm that you are installing `ignition-edifice` package on Ubuntu 20.04? On my system when I install 
```
apt install ingition-edifice
```
I can see that `libignition-gazebo5-dev` is being installed. Not 6
```
Setting up libignition-sensors5-air-pressure-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-physics4-tpe-dev:amd64 (4.3.0-1~focal) ...
Setting up libignition-launch4:amd64 (4.1.0-1~focal) ...
Setting up libignition-sensors5-magnetometer-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-rendering5-dev:amd64 (5.2.0-1~focal) ...
Setting up libignition-sensors5-lidar-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-camera-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-rendering-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-thermal-camera-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-imu-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-logical-camera-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-physics4-dev:amd64 (4.3.0-1~focal) ...
Setting up libignition-sensors5-depth-camera-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-gpu-lidar-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-sensors5-dev:amd64 (5.1.0-1~focal) ...
Setting up libignition-gazebo5-dev:amd64 (5.3.0-2~focal) ...
Setting up libignition-launch4-dev:amd64 (4.1.0-1~focal) ...
Setting up ignition-edifice (1.0.2-1~focal) ...

```

**Comment by liuqy1994** [comment]
Yes, as you can see, ignition-gazebo can exist in multiple versions on one system. Then, ignition-edifice is the[ fifth version](https://ignitionrobotics.org/docs/all/releases), on my system it is ignition-citadel, which is 6.x.
And, Can you launch and takeoff a quadrotor in ignition-edifice?

**Comment by Jaeyoung-Lim** [comment]
@liuqy1994 As written in the documentation, we only support ignition edifice for PX4 SITL. (Yes I can takeoff)

If you want to add support, it would be great if you can contribute it as a feature

**Comment by liuqy1994** [comment]
@Jaeyoung-Lim As your suggestion, I removed some of the higher version [components](https://ignitionrobotics.org/docs/edifice) that ign-gazebo depends on. According to the instructions on [this page](https://ignitionrobotics.org/docs/all/releases), the ign-gazebo version update creates an incompatible API which is probably the cause of the problem. Now, everything works fine and I can take off the quadrotor normally. 
Thank you very much for your help.
