### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ahcorde** [Auterion/px4-simulation-ignition#30]
Hi, 

I'm trying to understand this repository but I couldn't find enough information here or in the PX4 documentation. As far as I can see this repository contains 4 plugins:
 - barometer
 - magnetometer
 - gps
 - mavlink

I included the sensors plugins in this model `Tools/simulation/gz/models/x500-NoPlugin/model.sdf` and the mavlink plugin here `Tools/simulation/gz/models/x500/model.sdf` then I launched these plugins with the model inside the PX4 repo executing

```bash
reset & make px4_sitl gz_x500
```

Plugins are loaded properly because I can see the Gazebo traces but I have some questions/doubts:

 - Sensor topic are empty ? they are not plublising any data.
 - what's the use of the mavlink plugin? 

Can someone explain which are the different from using this repo or just the px4 oficial repository?

Thank you in advance

**Comment by dagar** [comment]
This was the first attempt using mavlink that was later replaced by the in tree gz-bridge.
